namespace: gitops-demo-argocd
nameSuffix: -development

labels:
  - pairs:
      env: production
    includeSelectors: true

resources:
  - ../../app1-base
# images:
#   - name: nginx
#     newTag: 1.14.1
