---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
spec:
  project: default
  source:
    repoURL: https://github.com/awesometown/gitops-demo.git
    path: argocd/development
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
spec:
  project: default
  source:
    repoURL: https://github.com/awesometown/gitops-demo.git
    path: argocd/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
spec:
  project: default
  source:
    repoURL: https://github.com/awesometown/gitops-demo.git
    path: argocd/production
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
